# Generated by Django 3.0.8 on 2020-07-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20200530_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
